name: TrueFormDesigns_dbt
version: 1.0.0
config-version: 2
profile: TrueFormDesigns_dbt
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  TrueFormDesigns_dbt:
    staging:
      +materialized: view
      +schema: ANALYTICS
      
    dimensions:
      +materialized: table
      +schema: ANALYTICS
      
    facts:
      +materialized: table
      +schema: ANALYTICS